apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dreamcatchers.fullname" . }}
  labels:
    app: {{ template "dreamcatchers.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $postgres := .Values.config.postgres }}
  postgres_url: {{ $postgres.url | b64enc }}
  postgres_password: {{ $postgres.password | b64enc }}
  {{- if .Values.config.pgadmin.enabled }}
  pgadmin_password: {{ .Values.config.pgadmin.password | b64enc }}
  {{- end }}
  smtp_password: {{ .Values.config.backend.smtpPassword | b64enc }}
  login_id: {{ .Values.config.backend.loginId | b64enc }}
  transaction_key: {{ .Values.config.backend.transactionKey | b64enc }}
