apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "dreamcatchers.fullname" . }}-backend
  labels:
    app: {{ template "dreamcatchers.name" . }}-backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "dreamcatchers.name" . }}-backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "dreamcatchers.fullname" . }}-backend
          image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 4000
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "dreamcatchers.fullname" . }}
                  key: postgres_url
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
