apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "dreamcatchers.fullname" . }}-studio
  labels:
    app: {{ template "dreamcatchers.name" . }}-studio
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "dreamcatchers.name" . }}-studio
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "dreamcatchers.fullname" . }}-studio
          image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 4000
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "dreamcatchers.fullname" . }}
                  key: postgres_url
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "dreamcatchers.fullname" . }}
                  key: postgres_host
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "dreamcatchers.fullname" . }}
                  key: postgres_database
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "dreamcatchers.fullname" . }}
                  key: postgres_port
            {{- if .Values.config.postgres.internal }}
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "dreamcatchers.sharedname" . }}-postgres-auth
                  key: POSTGRES_USER
            {{- else }}
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "dreamcatchers.fullname" . }}
                  key: postgres_username
            {{- end }}
            {{- if .Values.config.postgres.internal }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "dreamcatchers.sharedname" . }}-postgres-auth
                  key: POSTGRES_PASSWORD
            {{- else }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "dreamcatchers.fullname" . }}
                  key: postgres_password
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
